#!/usr/bin/env bash
# ============================================================
# IQ-TREE phylogenetic inference
# ============================================================
# Phylogenetic reconstruction based on the core genome
# alignment generated by Panaroo.
#
# IQ-TREE version: 3.0.1
#
# Developed by:
# Bui Quang Minh, Thomas Wong, Nhan Ly-Trong, Huaiyan Ren
# Contributed by:
# Lam-Tung Nguyen, Dominik Schrempf, Chris Bielow,
# Olga Chernomor, Michael Woodhams, Diep Thi Hoang, Heiko Schmidt
#
# NOTE:
# This script is provided for documentation and reproducibility
# purposes only. It does not need to be re-executed to reproduce
# the results included in this repository.
# ============================================================

set -euo pipefail

# -------------------------
# Input / Output
# -------------------------
ALIGNMENT="results/panaroo/core_gene_alignment_filtered.aln"
OUT_PREFIX="results/iqtree/salmonella_core"

mkdir -p results/iqtree

# -------------------------
# Run IQ-TREE
# -------------------------
iqtree2 \
  -s "$ALIGNMENT" \
  -m MFP \
  -B 1000 \
  --alrt 1000 \
  -T AUTO \
  --prefix "$OUT_PREFIX"
